AWSTemplateFormatVersion: "2010-09-09"
Description: Stack para prueba tecnica
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-053b0d53c279acc90  # ImageId de la imagen de Ubuntu 22.04 LTS
      InstanceType: t2.micro
      SubnetId: subnet-0f06d4a049090d708
      Tags:
        - Key: Name
          Value: test_ec2